name: Release CLI Package

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-pack:
    name: Build & Pack @bmi-calc/cli
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    env:
      # The `{VERSION}` is a placeholder for the package version.
      # It will be replaced by the actual version of the package based on `package.json`
      # during packaging process.
      FILENAME: bmi-calc@{VERSION}.tgz

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Bun
        id: setup-bun
        # Will use version from `.packageManager` in package.json
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: |
          printf '%s %s\n' "${{ steps.setup-bun.outputs.bun-path }}" "$(bun --revision)"
          bun install --frozen-lockfile

      - name: Build CLI package
        run: bun @cli build

      - name: Pack CLI package
        run: bun run pack cli --verbose --filename "${{ env.FILENAME }}"

      - name: Verify tarball package
        run: |
          ls -lh *.tgz
          echo ---
          tar -tvf "${{ env.FILENAME }}"

      - name: Generate SHA256 checksum
        run: |
          sha256sum *.tgz > checksums.txt
          cat checksums.txt

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.FILENAME }}
            checksums.txt
